apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: kgres-test
  namespace: default

spec:

   replicas: 3
   image: postgres:13

   database:
      size: 200Mi

   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: kgres-test-secret
              key: superUserPassword

      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: kgres-test-secret
              key: replicationUserPassword