apiVersion: kubegres.reactive-tech.io/v1
kind: Kubegres
metadata:
  name: {{ .Values.postgres.name }}
  namespace: default

spec:

   replicas: {{ .Values.postgres.replicas }}
   image: postgres:13

   database:
      size: {{ .Values.postgres.db_size }}

   env:
      - name: POSTGRES_PASSWORD
        valueFrom:
           secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: superUserPassword

      - name: POSTGRES_REPLICATION_PASSWORD
        valueFrom:
           secretKeyRef:
              name: {{ .Values.secrets.name }}
              key: replicationUserPassword