apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.name }}
  namespace: {{ .Values.secrets.namespace }}
type: Opaque
stringData:
  superUserPassword: {{ .Values.secrets.superUserPassword }}
  replicationUserPassword: {{ .Values.secrets.replicationUserPassword }}